
package remote.browse;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BrowseAvailabilityService", targetNamespace = "http://services.booking.service.web/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BrowseAvailabilityService {


    /**
     * 
     * @param idAgency
     * @param password
     * @param numberPerson
     * @param departureDate
     * @param arrivalDate
     * @return
     *     returns java.util.List<remote.browse.Offer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "browseAvailableRooms", targetNamespace = "http://services.booking.service.web/", className = "remote.browse.BrowseAvailableRooms")
    @ResponseWrapper(localName = "browseAvailableRoomsResponse", targetNamespace = "http://services.booking.service.web/", className = "remote.browse.BrowseAvailableRoomsResponse")
    @Action(input = "http://services.booking.service.web/BrowseAvailabilityService/browseAvailableRoomsRequest", output = "http://services.booking.service.web/BrowseAvailabilityService/browseAvailableRoomsResponse")
    public List<Offer> browseAvailableRooms(
        @WebParam(name = "idAgency", targetNamespace = "")
        String idAgency,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "arrivalDate", targetNamespace = "")
        XMLGregorianCalendar arrivalDate,
        @WebParam(name = "departureDate", targetNamespace = "")
        XMLGregorianCalendar departureDate,
        @WebParam(name = "numberPerson", targetNamespace = "")
        int numberPerson);

    /**
     * 
     * @param roomImName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getImageURL", targetNamespace = "http://services.booking.service.web/", className = "remote.browse.GetImageURL")
    @ResponseWrapper(localName = "getImageURLResponse", targetNamespace = "http://services.booking.service.web/", className = "remote.browse.GetImageURLResponse")
    @Action(input = "http://services.booking.service.web/BrowseAvailabilityService/getImageURLRequest", output = "http://services.booking.service.web/BrowseAvailabilityService/getImageURLResponse")
    public String getImageURL(
        @WebParam(name = "roomImName", targetNamespace = "")
        String roomImName);

}
