
package remote.browse;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BrowseAvailabilityServiceImplService", targetNamespace = "http://services.booking.service.web/", wsdlLocation = "http://localhost:8080/testsdfs/browse?wsdl")
public class BrowseAvailabilityServiceImplService
    extends Service
{

    private final static URL BROWSEAVAILABILITYSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BROWSEAVAILABILITYSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName BROWSEAVAILABILITYSERVICEIMPLSERVICE_QNAME = new QName("http://services.booking.service.web/", "BrowseAvailabilityServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/testsdfs/browse?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BROWSEAVAILABILITYSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BROWSEAVAILABILITYSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public BrowseAvailabilityServiceImplService() {
        super(__getWsdlLocation(), BROWSEAVAILABILITYSERVICEIMPLSERVICE_QNAME);
    }

    public BrowseAvailabilityServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BROWSEAVAILABILITYSERVICEIMPLSERVICE_QNAME, features);
    }

    public BrowseAvailabilityServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, BROWSEAVAILABILITYSERVICEIMPLSERVICE_QNAME);
    }

    public BrowseAvailabilityServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BROWSEAVAILABILITYSERVICEIMPLSERVICE_QNAME, features);
    }

    public BrowseAvailabilityServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BrowseAvailabilityServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BrowseAvailabilityService
     */
    @WebEndpoint(name = "BrowseAvailabilityServiceImplPort")
    public BrowseAvailabilityService getBrowseAvailabilityServiceImplPort() {
        return super.getPort(new QName("http://services.booking.service.web/", "BrowseAvailabilityServiceImplPort"), BrowseAvailabilityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BrowseAvailabilityService
     */
    @WebEndpoint(name = "BrowseAvailabilityServiceImplPort")
    public BrowseAvailabilityService getBrowseAvailabilityServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.booking.service.web/", "BrowseAvailabilityServiceImplPort"), BrowseAvailabilityService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BROWSEAVAILABILITYSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw BROWSEAVAILABILITYSERVICEIMPLSERVICE_EXCEPTION;
        }
        return BROWSEAVAILABILITYSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
