
package remote.booking;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookingService", targetNamespace = "http://services.booking.service.web/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookingService {


    /**
     * 
     * @param idAgency
     * @param firstName
     * @param lastName
     * @param password
     * @param loginId
     * @param chosenRooms
     * @param token
     * @return
     *     returns remote.booking.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeBooking", targetNamespace = "http://services.booking.service.web/", className = "remote.booking.MakeBooking")
    @ResponseWrapper(localName = "makeBookingResponse", targetNamespace = "http://services.booking.service.web/", className = "remote.booking.MakeBookingResponse")
    @Action(input = "http://services.booking.service.web/BookingService/makeBookingRequest", output = "http://services.booking.service.web/BookingService/makeBookingResponse")
    public Response makeBooking(
        @WebParam(name = "idAgency", targetNamespace = "")
        String idAgency,
        @WebParam(name = "loginId", targetNamespace = "")
        String loginId,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "FirstName", targetNamespace = "")
        String firstName,
        @WebParam(name = "LastName", targetNamespace = "")
        String lastName,
        @WebParam(name = "chosenRooms", targetNamespace = "")
        List<String> chosenRooms,
        @WebParam(name = "token", targetNamespace = "")
        String token);

}
