
package remote.partners;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PartnerShipManagementServcieImplService", targetNamespace = "http://services.booking.service.web/", wsdlLocation = "http://localhost:8080/testsdfs/partners?wsdl")
public class PartnerShipManagementServcieImplService
    extends Service
{

    private final static URL PARTNERSHIPMANAGEMENTSERVCIEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PARTNERSHIPMANAGEMENTSERVCIEIMPLSERVICE_EXCEPTION;
    private final static QName PARTNERSHIPMANAGEMENTSERVCIEIMPLSERVICE_QNAME = new QName("http://services.booking.service.web/", "PartnerShipManagementServcieImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/testsdfs/partners?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PARTNERSHIPMANAGEMENTSERVCIEIMPLSERVICE_WSDL_LOCATION = url;
        PARTNERSHIPMANAGEMENTSERVCIEIMPLSERVICE_EXCEPTION = e;
    }

    public PartnerShipManagementServcieImplService() {
        super(__getWsdlLocation(), PARTNERSHIPMANAGEMENTSERVCIEIMPLSERVICE_QNAME);
    }

    public PartnerShipManagementServcieImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PARTNERSHIPMANAGEMENTSERVCIEIMPLSERVICE_QNAME, features);
    }

    public PartnerShipManagementServcieImplService(URL wsdlLocation) {
        super(wsdlLocation, PARTNERSHIPMANAGEMENTSERVCIEIMPLSERVICE_QNAME);
    }

    public PartnerShipManagementServcieImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PARTNERSHIPMANAGEMENTSERVCIEIMPLSERVICE_QNAME, features);
    }

    public PartnerShipManagementServcieImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PartnerShipManagementServcieImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PartnerShipManagementService
     */
    @WebEndpoint(name = "PartnerShipManagementServcieImplPort")
    public PartnerShipManagementService getPartnerShipManagementServcieImplPort() {
        return super.getPort(new QName("http://services.booking.service.web/", "PartnerShipManagementServcieImplPort"), PartnerShipManagementService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PartnerShipManagementService
     */
    @WebEndpoint(name = "PartnerShipManagementServcieImplPort")
    public PartnerShipManagementService getPartnerShipManagementServcieImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.booking.service.web/", "PartnerShipManagementServcieImplPort"), PartnerShipManagementService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PARTNERSHIPMANAGEMENTSERVCIEIMPLSERVICE_EXCEPTION!= null) {
            throw PARTNERSHIPMANAGEMENTSERVCIEIMPLSERVICE_EXCEPTION;
        }
        return PARTNERSHIPMANAGEMENTSERVCIEIMPLSERVICE_WSDL_LOCATION;
    }

}
