
package remote.partners;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PartnerShipManagementService", targetNamespace = "http://services.booking.service.web/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PartnerShipManagementService {


    /**
     * 
     * @param password
     * @param userName
     * @param agencyName
     * @return
     *     returns remote.partners.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signUpUser", targetNamespace = "http://services.booking.service.web/", className = "remote.partners.SignUpUser")
    @ResponseWrapper(localName = "signUpUserResponse", targetNamespace = "http://services.booking.service.web/", className = "remote.partners.SignUpUserResponse")
    @Action(input = "http://services.booking.service.web/PartnerShipManagementService/signUpUserRequest", output = "http://services.booking.service.web/PartnerShipManagementService/signUpUserResponse")
    public Response signUpUser(
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "Password", targetNamespace = "")
        String password,
        @WebParam(name = "AgencyName", targetNamespace = "")
        String agencyName);

    /**
     * 
     * @param idAgency
     * @param password
     * @param userName
     * @return
     *     returns remote.partners.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCredentials", targetNamespace = "http://services.booking.service.web/", className = "remote.partners.UpdateCredentials")
    @ResponseWrapper(localName = "updateCredentialsResponse", targetNamespace = "http://services.booking.service.web/", className = "remote.partners.UpdateCredentialsResponse")
    @Action(input = "http://services.booking.service.web/PartnerShipManagementService/updateCredentialsRequest", output = "http://services.booking.service.web/PartnerShipManagementService/updateCredentialsResponse")
    public Response updateCredentials(
        @WebParam(name = "idAgency", targetNamespace = "")
        String idAgency,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "Password", targetNamespace = "")
        String password);

}
